In [1]:
import pandas as pd
import numpy as np

In [2]:
file_to_load = "../static/data/source/Crime_Data_from_2010_to_2019.csv"

In [3]:
crime_df = pd.read_csv(file_to_load)

In [4]:
crime_df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488

In [5]:
# dropping all cases where lat or long = 0
crime_df = crime_df[crime_df.LAT !=0]
crime_df = crime_df[crime_df.LON !=0]

In [6]:
# Rename Date OCC so i can pass it into next box
crime_df = crime_df.rename(columns = {'DATE OCC' : 'DATE_OCC'})
# crime_df.head()

In [7]:
# "DATE_OCC" is an object
crime_df["Date_Occur"] = crime_df["DATE_OCC"].str.extract('(../../....)', expand=True)
# crime_df.head()

In [8]:
# Create a var just for year
crime_df["Year"] = pd.DatetimeIndex(crime_df['Date_Occur']).year
# crime_df.head()

In [9]:
# Delete years 2010-2012
drop2010 = crime_df[crime_df["Year"] == 2010 ].index
drop2011 = crime_df[crime_df["Year"] == 2011 ].index
drop2012 = crime_df[crime_df["Year"] == 2012 ].index
crime_df.drop(drop2010, inplace = True)
crime_df.drop(drop2011, inplace = True)
crime_df.drop(drop2012, inplace = True)
crime_df.head()

,DR_NO,Date Rptd,DATE_OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON,Date_Occur,Year
611416,130814829,09/30/2013 12:00:00 AM,09/27/2013 12:00:00 AM,1800,8,West LA,838,1,310,BURGLARY,...,310.0,NaN,NaN,NaN,1000 GAYLEY AV,NaN,34.0620,-118.4480,09/27/2013,2013
611417,140107110,02/15/2014 12:00:00 AM,12/31/2013 12:00:00 AM,900,1,Central,192,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,341.0,NaN,NaN,NaN,HOPE,SANTA MONICA FY,34.0363,-118.2672,12/31/2013,2013
611418,131423822,10/01/2013 12:00:00 AM,10/01/2013 12:00:00 AM,1400,14,Pacific,1472,1,310,BURGLARY,...,310.0,NaN,NaN,NaN,7300 EARLDOM AV,NaN,33.9557,-118.4442,10/01/2013,2013
611419,132009209,04/21/2013 12:00:00 AM,04/21/2013 12:00:00 AM,1400,20,Olympic,2053,2,354,THEFT OF IDENTITY,...,354.0,NaN,NaN,NaN,1000 S HARVARD BL,NaN,34.0526,-118.3042,04/21/2013,2013
611420,130218066,08/27/2013 12:00:00 AM,08/26/2013 12:00:00 AM,2100,2,Rampart,299,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,930.0,NaN,NaN,NaN,1400 ALBANY ST,NaN,34.0417,-118.2750,08/26/2013,2013

In [10]:
# Rename Crm_Cd_Desc so i can pass it into next box
crime_df = crime_df.rename(columns = {'Crm Cd Desc' : 'Crm_Cd_Desc'})

In [11]:
# Start geting rid of rows where there are non-violent or domestic only crimes
crime_df = crime_df[crime_df.Crm_Cd_Desc !="ABORTION/ILLEGAL"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="BIGAMY"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="BRIBERY"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="BUNCO, ATTEMPT"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="CHILD ABANDONMENT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CHILD NEGLECT (SEE 300 W.I.C.)"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CONTEMPT OF COURT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="COUNTERFEIT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CREDIT CARDS, FRAUD USE ($950 & UNDER"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CREDIT CARDS, FRAUD USE ($950.01 & OVER)"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="CRUELTY TO ANIMALS"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="DISHONEST EMPLOYEE - GRAND THEFT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DISHONEST EMPLOYEE - PETTY THEFT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DISHONEST EMPLOYEE ATTEMPTED THEFT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DISRUPT SCHOOL"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DISTURBING THE PEACE"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DOCUMENT FORGERY / STOLEN FELONY"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DOCUMENT WORTHLESS ($200 & UNDER)"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="DOCUMENT WORTHLESS ($200.01 & OVER)"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="FAILURE TO YIELD"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="FAILURE TO DISPERSE"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="FALSE POLICE REPORT"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="GRAND THEFT / INSURANCE FRAUD"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="ILLEGAL DUMPING"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="INTIMATE PARTNER - AGGRAVATED ASSAULT"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="INTIMATE PARTNER - SIMPLE ASSAULT"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="LETTERS, LEWD  -  TELEPHONE CALLS, LEWD"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="LEWD/LASCIVIOUS ACTS WITH CHILD"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="SEX OFFENDER REGISTRANT OUT OF COMPLIANCE"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="TELEPHONE PROPERTY - DAMAGE"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="THEFT OF IDENTITY"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="THREATENING PHONE CALLS/LETTERS"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="UNAUTHORIZED COMPUTER ACCESS"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="VANDALISM - MISDEAMEANOR ($399 OR UNDER)"]

crime_df = crime_df[crime_df.Crm_Cd_Desc !="VIOLATION OF COURT ORDER"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="VIOLATION OF RESTRAINING ORDER"]
crime_df = crime_df[crime_df.Crm_Cd_Desc !="VIOLATION OF TEMPORARY RESTRAINING ORDER"]

In [12]:
# deleting columns we do not need
crime_df = crime_df.drop('Crm Cd', 1)
crime_df = crime_df.drop('Crm Cd 1', 1)
crime_df = crime_df.drop('Crm Cd 2', 1)
crime_df = crime_df.drop('Crm Cd 3', 1)
crime_df = crime_df.drop('Crm Cd 4', 1)
crime_df = crime_df.drop('Cross Street', 1)
crime_df = crime_df.drop('DATE_OCC', 1)
crime_df = crime_df.drop('Date Rptd', 1)
crime_df = crime_df.drop('DR_NO', 1)
crime_df = crime_df.drop('LOCATION', 1)
crime_df = crime_df.drop('Mocodes', 1)
crime_df = crime_df.drop('Part 1-2', 1)
crime_df = crime_df.drop('Premis Cd', 1)
crime_df = crime_df.drop('Status', 1)
crime_df = crime_df.drop('Status Desc', 1)
crime_df = crime_df.drop('TIME OCC', 1)
crime_df = crime_df.drop('Vict Age', 1)
crime_df = crime_df.drop('Vict Sex', 1)
crime_df = crime_df.drop('Vict Descent', 1)
crime_df = crime_df.drop('Weapon Used Cd', 1)
crime_df.head()

,AREA,AREA NAME,Rpt Dist No,Crm_Cd_Desc,Premis Desc,Weapon Desc,LAT,LON,Date_Occur,Year
611416,8,West LA,838,BURGLARY,OTHER BUSINESS,NaN,34.0620,-118.4480,09/27/2013,2013
611417,1,Central,192,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",PUBLIC STORAGE,NaN,34.0363,-118.2672,12/31/2013,2013
611418,14,Pacific,1472,BURGLARY,SINGLE FAMILY DWELLING,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",33.9557,-118.4442,10/01/2013,2013
611420,2,Rampart,299,CRIMINAL THREATS - NO WEAPON DISPLAYED,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",VERBAL THREAT,34.0417,-118.2750,08/26/2013,2013
611422,19,Mission,1984,ROBBERY,STREET,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",34.2282,-118.4536,08/22/2013,2013

In [13]:
# for col in crime_df.columns:
#     print(col)

In [14]:
#rename columns so that they work better for this
crime_df = crime_df.rename(columns = {"Crm_Cd_Desc" : "Crime_Type" , "Premis Desc" : "Premise" , "Weapon Desc" : "Weapon" , "AREA " : "LAPD_Area" , "AREA NAME": "LAPD_Area_Name"})
crime_df.head()

,LAPD_Area,LAPD_Area_Name,Rpt Dist No,Crime_Type,Premise,Weapon,LAT,LON,Date_Occur,Year
611416,8,West LA,838,BURGLARY,OTHER BUSINESS,NaN,34.0620,-118.4480,09/27/2013,2013
611417,1,Central,192,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",PUBLIC STORAGE,NaN,34.0363,-118.2672,12/31/2013,2013
611418,14,Pacific,1472,BURGLARY,SINGLE FAMILY DWELLING,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",33.9557,-118.4442,10/01/2013,2013
611420,2,Rampart,299,CRIMINAL THREATS - NO WEAPON DISPLAYED,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",VERBAL THREAT,34.0417,-118.2750,08/26/2013,2013
611422,19,Mission,1984,ROBBERY,STREET,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",34.2282,-118.4536,08/22/2013,2013

In [15]:
# Re-org 
crime_df = crime_df[["Year" , "Date_Occur" , "LAPD_Area" , "LAPD_Area_Name" , "LAT", "LON", "Crime_Type", "Premise" , "Weapon"]]
crime_df.head()

,Year,Date_Occur,LAPD_Area,LAPD_Area_Name,LAT,LON,Crime_Type,Premise,Weapon
611416,2013,09/27/2013,8,West LA,34.0620,-118.4480,BURGLARY,OTHER BUSINESS,NaN
611417,2013,12/31/2013,1,Central,34.0363,-118.2672,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",PUBLIC STORAGE,NaN
611418,2013,10/01/2013,14,Pacific,33.9557,-118.4442,BURGLARY,SINGLE FAMILY DWELLING,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)"
611420,2013,08/26/2013,2,Rampart,34.0417,-118.2750,CRIMINAL THREATS - NO WEAPON DISPLAYED,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",VERBAL THREAT
611422,2013,08/22/2013,19,Mission,34.2282,-118.4536,ROBBERY,STREET,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)"

In [16]:
#Recode weapons
crime_df['Weapon'] = crime_df['Weapon'].replace(['BELT FLAILING INSTRUMENT/CHAIN'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BLACKJACK'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BLUNT INSTRUMENT'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BOARD'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BOTTLE'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BRASS KNUCKLES'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['CLUB/BAT'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['CONCRETE BLOCK/BRICK'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['HAMMER'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['PIPE/METAL PIPE'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['ROCK/THROWN OBJECT'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['STICK'],'Blunt Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['TIRE IRON'],'Blunt Instrument')

crime_df['Weapon'] = crime_df['Weapon'].replace(['BOMB THREAT'],'Explosive')
crime_df['Weapon'] = crime_df['Weapon'].replace(['EXPLOXIVE DEVICE'],'Explosive')

crime_df['Weapon'] = crime_df['Weapon'].replace(['FIRE'],'Fire')

crime_df['Weapon'] = crime_df['Weapon'].replace(['AIR PISTOL/REVOLVER/RIFLE/BB GUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['ANTIQUE FIREARM'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['ASSAULT WEAPON/UZI/AK47/ETC'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['AUTOMATIC WEAPON/SUB-MACHINE GUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['HAND GUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['HECKLER & KOCH 93 SEMIAUTOMATIC ASSAULT RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['M1-1 SEMIAUTOMATIC ASSAULT RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['M-14 SEMIAUTOMATIC ASSAULT RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['MAC-10 SEMIAUTOMATIC ASSAULT WEAPON'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['MAC-11 SEMIAUTOMATIC ASSAULT WEAPON'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['OTHER FIREARM'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['RELIC FIREARM'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['REVOLVER'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SAWED OFF RIFLE/SHOTGUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SEMI-AUTOMATIC PISTOL'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SEMI-AUTOMATIC RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SHOTGUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SIMULATED GUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['STARTER PISTOL/REVOLVER'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['TOY GUN'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['UNK TYPE SEMIAUTOMATIC ASSAULT RIFLE'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['UNKNOWN FIREARM'],'Firearm')
crime_df['Weapon'] = crime_df['Weapon'].replace(['UZI SEMIAUTOMATIC ASSAULT RIFLE'],'Firearm')

crime_df['Weapon'] = crime_df['Weapon'].replace(['VEHICLE'],'Motor Vehicle')

crime_df['Weapon'] = crime_df['Weapon'].replace(['PHYSICAL PRESENCE'],'Personal Weapons')
crime_df['Weapon'] = crime_df['Weapon'].replace(['STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)'],'Personal Weapons')

crime_df['Weapon'] = crime_df['Weapon'].replace(['CAUSTIC CHEMICAL/POISON'],'Poison')
crime_df['Weapon'] = crime_df['Weapon'].replace(['LIQUOR/DRUGS'],'Poison')

crime_df['Weapon'] = crime_df['Weapon'].replace(['AXE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BOW AND ARROW'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['BOWIE KNIFE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['CLEAVER'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['DIRK/DAGGER'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['FOLDING KNIFE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['GLASS'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['ICE PICK'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['KITCHEN KNIFE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['KNIFE WITH BLADE 6INCHES OR LESS'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['KNIFE WITH BLADE OVER 6 INCHES IN LENGTH'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['MACHETE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['OTHER CUTTING INSTRUMENT'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['OTHER KNIFE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['RAZOR'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['RAZOR BLADE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SCISSORS'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SCREWDRIVER'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['STRAIGHT RAZOR'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SWITCH BLADE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SWORD'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SYRINGE'],'Sharp Instrument')
crime_df['Weapon'] = crime_df['Weapon'].replace(['UNKNOWN TYPE CUTTING INSTRUMENT'],'Sharp Instrument')

crime_df['Weapon'] = crime_df['Weapon'].replace(['DEMAND NOTE'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['DOG/ANIMAL (SIC ANIMAL ON)'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['FIXED OBJECT'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['MACE/PEPPER SPRAY'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['MARTIAL ARTS WEAPONS'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['ROPE/LIGATURE'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['SCALDING LIQUID'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['STUN GUN'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['UNKNOWN WEAPON/OTHER WEAPON'],'Unk or Other')
crime_df['Weapon'] = crime_df['Weapon'].replace(['VERBAL THREAT'],'Unk or Other')

In [17]:
# JUST BE SURE
crime_df["Weapon"].unique()

array([nan, 'Personal Weapons', 'Unk or Other', 'Firearm',
       'Blunt Instrument', 'Sharp Instrument', 'Motor Vehicle',
       'Explosive', 'Fire', 'Poison'], dtype=object)

In [18]:
# Recode premis Crm_Cd_Desc 
crime_df['Premise'] = crime_df['Premise'].replace(['AUTOMATED TELLER MACHINE (ATM)'],'Bank')
crime_df['Premise'] = crime_df['Premise'].replace(['BANK'],'Bank')
crime_df['Premise'] = crime_df['Premise'].replace(['BANK DROP BOX/MONEY DROP-OUTSIDE OF BANK*'],'Bank')
crime_df['Premise'] = crime_df['Premise'].replace(['BANKING INSIDE MARKET-STORE *'],'Bank')
crime_df['Premise'] = crime_df['Premise'].replace(['CREDIT UNION'],'Bank')
crime_df['Premise'] = crime_df['Premise'].replace(['DRIVE THRU BANKING (WINDOW)*'],'Bank')
crime_df['Premise'] = crime_df['Premise'].replace(['SAVINGS & LOAN'],'Bank')

crime_df['Premise'] = crime_df['Premise'].replace(['ABATEMENT LOCATION'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['CHEMICAL STORAGE/MANUFACTURING PLANT'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['CONSTRUCTION SITE'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['ENERGY PLANT/FACILITY'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['FACTORY'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['GARMENT MANUFACTURER'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['MANUFACTURING COMPANY'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV\'S/MOTORHOME'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['NUCLEAR FACILITY'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['OIL REFINERY'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['RECYCLING CENTER'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['SEWAGE FACILITY/PIPE'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['TOW YARD*'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['WAREHOUSE'],'Construction/Industrial Area')
crime_df['Premise'] = crime_df['Premise'].replace(['WATER FACILITY'],'Construction/Industrial Area')

crime_df['Premise'] = crime_df['Premise'].replace(['DETENTION/JAIL FACILITY'],'Detention Facility')

crime_df['Premise'] = crime_df['Premise'].replace(['HOTEL'],'Hotel/Motel')
crime_df['Premise'] = crime_df['Premise'].replace(['MOTEL'],'Hotel/Motel')

crime_df['Premise'] = crime_df['Premise'].replace(['ABANDONED BUILDING ABANDONED HOUSE'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['APARTMENT/CONDO COMMON LAUNDRY ROOM'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['BALCONY*'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['CONDOMINIUM/TOWNHOUSE'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['DRIVEWAY'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['FOSTER HOME BOYS OR GIRLS*'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['GROUP HOME'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['HIGH-RISE BUILDING'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['MISSIONS/SHELTERS'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER RESIDENCE'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['PATIO*'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['PORCH, RESIDENTIAL'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['PROJECT/TENEMENT/PUBLIC HOUSING'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['SINGLE FAMILY DWELLING'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['SINGLE RESIDENCE OCCUPANCY (SRO\'S) LOCATIONS'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['SHORT-TERM VACATION RENTAL'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['STORAGE SHED'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['TOOL SHED*'],'House/Apartment/Yard')
crime_df['Premise'] = crime_df['Premise'].replace(['TRANSITIONAL HOUSING/HALFWAY HOUSE'],'House/Apartment/Yard')


crime_df['Premise'] = crime_df['Premise'].replace(['MEDICAL MARIJUANA FACILITIES/BUSINESSES'],'Marijuana Business')

crime_df['Premise'] = crime_df['Premise'].replace(['ABORTION CLINIC/ABORTION FACILITY*'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['DAY CARE/ADULTS*'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['DAY CARE/CHILDREN*'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['HOSPICE'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['HOSPITAL'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['MEDICAL/DENTAL OFFICES'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['METHADONE CLINIC'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['NURSING/CONVALESCENT/RETIREMENT HOME'],'Medical/Care Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['VISION CARE FACILITY*'],'Medical/Care Facility')

crime_df['Premise'] = crime_df['Premise'].replace(['TRUCK, COMMERICAL'],'Motor Vehicle')
crime_df['Premise'] = crime_df['Premise'].replace(['VEHICLE, PASSENGER/TRUCK'],'Motor Vehicle')

crime_df['Premise'] = crime_df['Premise'].replace(['BEACH'],'Natural Area')
crime_df['Premise'] = crime_df['Premise'].replace(['DAM/RESERVOIR'],'Natural Area')
crime_df['Premise'] = crime_df['Premise'].replace(['RIVER BED*'],'Natural Area')

crime_df['Premise'] = crime_df['Premise'].replace(['BUS, SCHOOL, CHURCH'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['CEMETARY*'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['CYBERSPACE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['DELIVERY SERVICE (FED EX, UPS, COURIERS,COURIER SERVICE)*'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['DEPT OF DEFENSE FACILITY'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['ELEVATOR'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['FIRE STATION'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['GOVERNMENT FACILITY (FEDERAL,STATE, COUNTY & CITY)'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['HARBOR FRWY STATION (NOT LINE SPECIFIC)'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['MAIL BOX'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['MORTUARY'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER/OUTSIDE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER PREMISE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['POLICE FACILITY'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['PUBLIC STORAGE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['RETIRED (DUPLICATE) DO NOT USE THIS CODE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['SLIPS/DOCK/MARINA/BOAT'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['STAIRWELL*'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['STUDIO (FILM/PHOTOGRAPHIC/MUSIC)'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['TACTICAL SIGNIFICANCE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['TRAIN TRACKS'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['TRANSIENT ENCAMPMENT'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['TRASH CAN/TRASH DUMPSTER'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['VACANT LOT'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['VALET'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['VETERINARIAN/ANIMAL HOSPITAL'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['WEBSITE'],'Other')
crime_df['Premise'] = crime_df['Premise'].replace(['YARD (RESIDENTIAL/BUSINESS)'],'Other')

crime_df['Premise'] = crime_df['Premise'].replace(['FINANCE COMPANY'],'Other Business Location')
crime_df['Premise'] = crime_df['Premise'].replace(['OFFICE BUILDING/OFFICE'],'Other Business Location')
crime_df['Premise'] = crime_df['Premise'].replace(['TELECOMMUNICATION FACILITY/LOCATION'],'Other Business Location')

crime_df['Premise'] = crime_df['Premise'].replace(['AMUSEMENT PARK*'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['COLISEUM'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['CONVENTION CENTER'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['CULTURAL SIGNIFICANCE/MONUMENT'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['LIBRARY'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['MASS GATHERING LOCATION'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['MUSCLE BEACH'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['MUSEUM'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['PARK/PLAYGROUND'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['POOL-PUBLIC/OUTDOOR OR INDOOR*'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['POST OFFICE'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['PUBLIC RESTROOM(INDOORS-INSIDE)'],'Other Public Place')
crime_df['Premise'] = crime_df['Premise'].replace(['PUBLIC RESTROOM/OUTSIDE*'],'Other Public Place')

crime_df['Premise'] = crime_df['Premise'].replace(['AIRCRAFT'],'Other Vehicle')
crime_df['Premise'] = crime_df['Premise'].replace(['AMTRAK TRAIN'],'Other Vehicle')
crime_df['Premise'] = crime_df['Premise'].replace(['BUS-CHARTER/PRIVATE'],'Other Vehicle')
crime_df['Premise'] = crime_df['Premise'].replace(['GREYHOUND OR INTERSTATE BUS'],'Other Vehicle')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER INTERSTATE, CHARTER BUS'],'Other Vehicle')
crime_df['Premise'] = crime_df['Premise'].replace(['TAXI'],'Other Vehicle')

crime_df['Premise'] = crime_df['Premise'].replace(['GARAGE/CARPORT'],'Parking Lot')
crime_df['Premise'] = crime_df['Premise'].replace(['ORANGE LINE PARKING LOT'],'Parking Lot')
crime_df['Premise'] = crime_df['Premise'].replace(['PARKING LOT'],'Parking Lot')
crime_df['Premise'] = crime_df['Premise'].replace(['PARKING UNDERGROUND/BUILDING'],'Parking Lot')
crime_df['Premise'] = crime_df['Premise'].replace(['VEHICLE STORAGE LOT (CARS, TRUCKS, RV\'S, BOATS, TRAILERS, ETC.)'],'Parking Lot')

crime_df['Premise'] = crime_df['Premise'].replace(['BLUE LINE (ABOVE GROUND SURFACE TRAIN)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['BUS DEPOT/TERMINAL, OTHER THAN MTA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['BUS STOP'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['BUS STOP/LAYOVER (ALSO QUERY 124)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['GREEN LINE (I-105 FWY LEVEL TRAIN)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['METROLINK TRAIN'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GREEN LINE - AVIATION/LAX'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - WOODLEY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - 7TH AND METRO CENTER'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA BUS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA PROPERTY OR PARKING LOT'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MUNICIPAL BUS LINE INCLUDES LADOT/DASH'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER RR TRAIN (UNION PAC, SANTE FE ETC'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['REDLINE (SUBWAY TRAIN)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['REDLINE ENTRANCE/EXIT'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['REDLINE SUBWAY MEZZANINE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['REDLINE SUBWAY PLATFORM'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['REDLINE SUBWAY RAIL CAR (INSIDE TRAIN)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['REDLINE SUBWAY TUNNEL'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['TERMINAL, OTHER THAN MTA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['TRAIN DEPOT/TERMINAL, OTHER THAN MTA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['TRAIN, OTHER THAN MTA (ALSO QUERY 809/810/811)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['TRAM/STREETCAR(BOXLIKE WAG ON RAILS)*'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['TRANSPORTATION FACILITY (AIRPORT)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - UNION STATION'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['THE GROVE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['THE BEVERLY CENTER'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['THE BEVERLY CONNECTION'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - HOLLYWOOD/VINE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - WESTLAKE/MACARTHUR PARK'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GREEN LINE - HARBOR FWY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - PERSHING SQUARE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - CHATSWORTH'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - VERMONT/BEVERLY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - VERMONT/SANTA MONICA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - NORTH HOLLYWOOD'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['LA UNION STATION (NOT LINE SPECIFIC)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - PICO'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO/WESTERN'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - HOLLYWOOD/HIGHLAND'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - SEPULVEDA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - 7TH AND METRO CENTER'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO/VERMONT'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - LITTLE TOKYO/ARTS DISTRICT'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - FARMDALE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO/BUNDY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - 7TH AND METRO CENTER'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO/LA BREA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - HIGHLAND PARK'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['7TH AND METRO CENTER (NOT LINE SPECIFIC)'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - WASHINGTON'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - WILSHIRE/WESTERN'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - VERMONT/SUNSET'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - UNION STATION'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - UNION STATION'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - CIVIC CENTER/GRAND PARK'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - UNIVERSAL CITY/STUDIO CITY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO/CRENSHAW'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - CHINATOWN'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GREEN LINE - AVALON'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - UNION STATION'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - WILSHIRE/VERMONT'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - MARIACHI PLAZA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO PARK/USC'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - WILSHIRE/VERMONT'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - PICO'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - VERNON'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - BALBOA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - PALMS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - EXPO/SEPULVEDA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - JEFFERSON/USC'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - SOTO'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - LATTC/ORTHO INSTITUTE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - RED LINE - HOLLYWOOD/WESTERN'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - 103RD/WATTS TOWERS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - VAN NUYS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - HARBOR GATEWAY TRANSIT CTR'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - LINCOLN/CYPRESS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - NORTH HOLLYWOOD'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - WESTWOOD/RANCHO PARK'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - EXPO LINE - LA CIENEGA/JEFFERSON'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - 7TH AND METRO CENTER'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - WOODMAN'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - RESEDA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - INDIANA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - PICO/ALISO'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - PERSHING SQUARE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - CANOGA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - WILSHIRE/NORMANDIE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - LAUREL CANYON'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - GRAND/LATTC'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - BLUE LINE - SAN PEDRO'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - HERITAGE SQ'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - WESTLAKE/MACARTHUR PARK'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - DOWNTOWN STREET STOPS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - SLAUSON'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - WARNER CTR'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - PURPLE LINE - CIVIC CENTER/GRAND PARK'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - VALLEY COLLEGE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - HARBOR FWY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - MANCHESTER'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - PIERCE COLLEGE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - TAMPA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - GOLD LINE - SOUTHWEST MUSEUM'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - SHERMAN WAY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - DE SOTO'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - ROSCOE'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - PACIFIC COAST HWY'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - ROSECRANS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - CAL STATE LA'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - 37TH ST/USC'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - SAN PEDRO STREET STOPS'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - ORANGE LINE - NORDHOFF'],'Public Transit')
crime_df['Premise'] = crime_df['Premise'].replace(['MTA - SILVER LINE - LAC/USC MEDICAL CENTER'],'Public Transit')


crime_df['Premise'] = crime_df['Premise'].replace(['CHURCH/CHAPEL (CHANGED 03-03 FROM CHURCH/TEMPLE)'],'Religious Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['MOSQUE*'],'Religious Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER PLACE OF WORSHIP'],'Religious Facility')
crime_df['Premise'] = crime_df['Premise'].replace(['SYNAGOGUE/TEMPLE'],'Religious Facility')

crime_df['Premise'] = crime_df['Premise'].replace(['BAR/COCKTAIL/NIGHTCLUB'],'Restaurant/Bar')
crime_df['Premise'] = crime_df['Premise'].replace(['BAR/SPORTS BAR (OPEN DAY & NIGHT)'],'Restaurant/Bar')
crime_df['Premise'] = crime_df['Premise'].replace(['CATERING/ICE CREAM TRUCK'],'Restaurant/Bar')
crime_df['Premise'] = crime_df['Premise'].replace(['DRIVE THRU*'],'Restaurant/Bar')
crime_df['Premise'] = crime_df['Premise'].replace(['NIGHT CLUB (OPEN EVENINGS ONLY)'],'Restaurant/Bar')
crime_df['Premise'] = crime_df['Premise'].replace(['RESTAURANT/FAST FOOD'],'Restaurant/Bar')

crime_df['Premise'] = crime_df['Premise'].replace(['ARCADE,GAME ROOM/VIDEO GAMES (EXAMPLE CHUCKIE CHEESE)*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['AUTO DEALERSHIP (CHEVY, FORD, BMW, MERCEDES, ETC.)'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['AUTO REPAIR SHOP'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['AUTO SALES LOT'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['AUTO SUPPLY STORE*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['BEAUTY SUPPLY STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['BEAUTY/BARBER SHOP'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['BOOK STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['BOWLING ALLEY*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['CAR WASH'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['CELL PHONE STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['CHECK CASHING*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['CLEANER/LAUNDROMAT'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['CLOTHING STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEET\'S, ETC.)'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['COMPUTER SERVICES/REPAIRS/SALES'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['DEPARTMENT STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['DISCOUNT STORE (99 CENT,DOLLAR,ETC.'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['DIY CENTER (LOWE\'S,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['DRUG STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['ELECTRONICS STORE (IE:RADIO SHACK, ETC.)'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['ENTERTAINMENT/COMEDY CLUB (OTHER)'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['EQUIPMENT RENTAL'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['ESCALATOR*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['FURNITURE STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['GAS STATION'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['GUN/SPORTING GOODS'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['HARDWARE/BUILDING SUPPLY'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['JEWELRY STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['LAUNDROMAT'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['LIQUOR STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['MARKET'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['MASSAGE PARLOR'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['MEMBERSHIP STORE (COSTCO,SAMS CLUB)*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['MINI-MART'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['NAIL SALON'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['NURSERY/FLOWER SHOP'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['OPTICAL OFFICE INSIDE STORE OR SUPERMARKET*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER BUSINESS'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['OTHER STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['PAWN SHOP'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['PET STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['PHARMACY INSIDE STORE OR SUPERMARKET*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['RECORD-CD MUSIC/COMPUTER GAME STORE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['SEX ORIENTED/BOOK STORE/STRIP CLUB/GENTLEMAN\'S CLUB'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['SHOPPING MALL (COMMON AREA)'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['SURPLUS SURVIVAL STORE'],'Retail Location')                                                      
crime_df['Premise'] = crime_df['Premise'].replace(['SWAP MEET'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['TATTOO PARLOR*'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['THEATRE/MOVIE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['TOBACCO SHOP'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['TV/RADIO/APPLIANCE'],'Retail Location')
crime_df['Premise'] = crime_df['Premise'].replace(['VIDEO RENTAL STORE'],'Retail Location')

crime_df['Premise'] = crime_df['Premise'].replace(['COLLEGE/JUNIOR COLLEGE/UNIVERSITY'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['ELEMENTARY SCHOOL'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['FRAT HOUSE/SORORITY/DORMITORY'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['HIGH SCHOOL'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['JUNIOR HIGH SCHOOL'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['PRIVATE SCHOOL/PRESCHOOL'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['SPECIALTY SCHOOL/OTHER'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['TRADE SCHOOL (MEDICAL-TECHNICAL-BUSINESS)*'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['old'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['old'],'School/College')
crime_df['Premise'] = crime_df['Premise'].replace(['old'],'School/College')
                                                           
crime_df['Premise'] = crime_df['Premise'].replace(['BASKETBALL COURTS'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['DODGER STADIUM'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['HANDBALL COURTS'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['GOLF COURSE*'],'Sports Venue')                                                          
crime_df['Premise'] = crime_df['Premise'].replace(['HEALTH SPA/GYM'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['HOCKEY RINK/ICE HOCKEY'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['HORSE RACING/SANTA ANITA PARK*'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['SKATEBOARD FACILITY/SKATEBOARD PARK*'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['SKATING RINK*'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['SPORTS ARENA'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['SPORTS VENUE, OTHER'],'Sports Venue')
crime_df['Premise'] = crime_df['Premise'].replace(['STAPLES CENTER *'],'Sports Venue')

crime_df['Premise'] = crime_df['Premise'].replace(['ALLEY'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['FREEWAY'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['PAY PHONE'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['PEDESTRIAN OVERCROSSING'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['SIDEWALK'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['STREET'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['TUNNEL'],'Street/Alley/Sidewalk')
crime_df['Premise'] = crime_df['Premise'].replace(['UNDERPASS/BRIDGE*'],'Street/Alley/Sidewalk')

In [19]:
# JUST BE SURE
crime_df["Premise"].unique()

array(['Retail Location', 'Other', 'House/Apartment/Yard',
       'Street/Alley/Sidewalk', 'Parking Lot', 'Hotel/Motel',
       'Sports Venue', 'School/College', 'Motor Vehicle',
       'Restaurant/Bar', 'Medical/Care Facility', 'Bank',
       'Other Business Location', 'Other Public Place',
       'Construction/Industrial Area', 'Public Transit',
       'Religious Facility', 'Natural Area', 'Marijuana Business',
       'Detention Facility', 'Other Vehicle', nan], dtype=object)

In [20]:
# Code crime types into UCR data categories 
# crime_df["Crime_Type"].unique()
crime_df["Premise"].value_counts()

Street/Alley/Sidewalk           384283
House/Apartment/Yard            310785
Retail Location                 157601
Parking Lot                     139663
Motor Vehicle                    36223
Other                            29916
Restaurant/Bar                   26044
School/College                   22411
Public Transit                   17235
Other Public Place               13096
Hotel/Motel                       8288
Medical/Care Facility             7546
Construction/Industrial Area      5839
Sports Venue                      5083
Other Business Location           3738
Religious Facility                3122
Bank                              2240
Natural Area                      1338
Marijuana Business                 751
Other Vehicle                      718
Detention Facility                 467
Name: Premise, dtype: int64

In [21]:
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['FALSE IMPRISONMENT'],'Abduction/Kidnap')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['KIDNAPPING'],'Abduction/Kidnap')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['KIDNAPPING - GRAND ATTEMPT'],'Abduction/Kidnap')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ARSON'],'Arson')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['AGGRAVATED ASSAULT'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ASSAULT'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ASSAULT WITH DEADLY WEAPON'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BATTERY ON A FIREFIGHTER'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BATTERY POLICE (SIMPLE)'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BATTERY - SIMPLE ASSAULT'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['OTHER ASSAULT'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SHOTS FIRED AT INHABITED DWELLING'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT'],'Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THROWING OBJECT AT MOVING VEHICLE'],'Assault')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BURGLARY'],'Burglary')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BURGLARY, ATTEMPTED'],'Burglary')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BURGLARY FROM VEHICLE'],'Burglary')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BURGLARY FROM VEHICLE, ATTEMPTED'],'Burglary')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)'],'Crimes Against Children')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CHILD PORNOGRAPHY'],'Crimes Against Children')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CHILD STEALING'],'Crimes Against Children')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CRIMINAL HOMICIDE'],'Homicide')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['LYNCHING'],'Homicide')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['LYNCHING - ATTEMPTED'],'Homicide')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['MANSLAUGHTER, NEGLIGENT'],'Homicide')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['HUMAN TRAFFICKING - COMMERCIAL SEX ACTS'],'Human Traffic/Prost')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE'],'Human Traffic/Prost')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PANDERING'],'Human Traffic/Prost')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PIMPING'],'Human Traffic/Prost')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BATTERY WITH SEXUAL CONTACT'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CHILD ANNOYING (17YRS & UNDER)'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['INDECENT EXPOSURE'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['LEWD CONDUCT'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ORAL COPULATION'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PEEPING TOM'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['RAPE, ATTEMPTED'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['RAPE, FORCIBLE'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SEXUAL PENETRATION W/FOREIGN OBJECT'],'Rape/Sexual Assault')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH'],'Rape/Sexual Assault')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ATTEMPTED ROBBERY'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['DRUNK ROLL'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['EXTORTION'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PICKPOCKET'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PICKPOCKET, ATTEMPT'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PURSE SNATCHING'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PURSE SNATCHING - ATTEMPT'],'Robbery')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['ROBBERY'],'Robbery')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BIKE - ATTEMPTED STOLEN'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BIKE - STOLEN'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BOAT - STOLEN'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BUNCO, GRAND THEFT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BUNCO, PETTY THEFT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $400'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & UNDER'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['DRIVING WITHOUT OWNER CONSENT (DWOC)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['GRAND THEFT / AUTO REPAIR'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PETTY THEFT - AUTO REPAIR'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SHOPLIFTING - ATTEMPT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SHOPLIFTING-GRAND THEFT ($950.01 & OVER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['SHOPLIFTING - PETTY THEFT ($950 & UNDER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT, COIN MACHINE - ATTEMPT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT, COIN MACHINE - GRAND ($950.01 & OVER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT, COIN MACHINE - PETTY ($950 & UNDER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT FROM PERSON - ATTEMPT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT FROM MOTOR VEHICLE - ATTEMPT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT, PERSON'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT PLAIN - ATTEMPT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['THEFT PLAIN - PETTY ($950 & UNDER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['TILL TAP - ATTEMPT'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['TILL TAP - GRAND THEFT ($950.01 & OVER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['TILL TAP - PETTY ($950 & UNDER)'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['VEHICLE - ATTEMPT STOLE'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['VEHICLE - ATTEMPT STOLEN'],'Theft')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['VEHICLE - STOLEN'],'Theft')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BLOCKING DOOR INDUCTION CENTER'],'Tresspass')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['PROWLER'],'Tresspass')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['TRESPASSING'],'Tresspass')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)'],'Vandalism')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BOMB SCARE'],'Weapons Violation')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['BRANDISH WEAPON'],'Weapons Violation')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['DISCHARGE FIREARMS/SHOTS FIRED'],'Weapons Violation')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['WEAPONS POSSESSION/BOMBING'],'Weapons Violation')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)'],'Weapons Violation')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['FIREARMS RESTRAINING ORDER (FIREARMS RO)'],'Weapons Violation')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['FIREARMS TEMPORARY RESTRAINING ORDER (TEMP FIREARMS RO)'],'Weapons Violation')

crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CONTRIBUTING'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CONSPIRACY'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['CRIMINAL THREATS - NO WEAPON DISPLAYED'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['DRUGS, TO A MINOR'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['INCITING A RIOT'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['OTHER MISCELLANEOUS CRIME'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['RECKLESS DRIVING'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['RESISTING ARREST'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['STALKING'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['TRAIN WRECKING'],'Other')
crime_df['Crime_Type'] = crime_df['Crime_Type'].replace(['VEHICLE - MOTORIZED SCOOTERS, BICYCLES, AND WHEELCHAIRS'],'Other')

In [22]:
crime_df["Crime_Type"].unique()

array(['Burglary', 'Theft', 'Other', 'Robbery', 'Tresspass', 'Assault',
       'Rape/Sexual Assault', 'Vandalism', 'Arson',
       'Crimes Against Children', 'Weapons Violation', 'Abduction/Kidnap',
       'Homicide', 'Human Traffic/Prost'], dtype=object)

In [23]:
crime_df["Crime_Type"].value_counts()

Theft                      454981
Burglary                   223580
Assault                    211049
Vandalism                   81602
Robbery                     69809
Other                       54369
Rape/Sexual Assault         32242
Tresspass                   17800
Weapons Violation           16931
Crimes Against Children      6106
Arson                        2562
Abduction/Kidnap             2401
Homicide                     1938
Human Traffic/Prost          1161
Name: Crime_Type, dtype: int64

In [23]:
#After some thoughts, decided to drop some other crime types to streamline the data
crime_df = crime_df[crime_df.Crime_Type !="Other"]
crime_df = crime_df[crime_df.Crime_Type !="Tresspass"]
crime_df = crime_df[crime_df.Crime_Type !="Vandalism"]
crime_df = crime_df[crime_df.Crime_Type !="Weapons Violation"]
crime_df = crime_df[crime_df.Crime_Type !="Crimes Against Children"]
crime_df = crime_df[crime_df.Crime_Type !="Abduction/Kidnap"]
crime_df = crime_df[crime_df.Crime_Type !="Human Traffic/Prost"]

In [24]:
crime_df["Crime_Type"].value_counts()

Theft                  454981
Burglary               223580
Assault                211049
Robbery                 69809
Rape/Sexual Assault     32242
Arson                    2562
Homicide                 1938
Name: Crime_Type, dtype: int64

In [25]:
# set an index
crime_df.reset_index(drop = True, inplace = True)
crime_df.head()

,Year,Date_Occur,LAPD_Area,LAPD_Area_Name,LAT,LON,Crime_Type,Premise,Weapon
0,2013,09/27/2013,8,West LA,34.0620,-118.4480,Burglary,Retail Location,NaN
1,2013,12/31/2013,1,Central,34.0363,-118.2672,Theft,Other,NaN
2,2013,10/01/2013,14,Pacific,33.9557,-118.4442,Burglary,House/Apartment/Yard,Personal Weapons
3,2013,08/22/2013,19,Mission,34.2282,-118.4536,Robbery,Street/Alley/Sidewalk,Personal Weapons
4,2013,05/17/2013,21,Topanga,34.1865,-118.6146,Assault,House/Apartment/Yard,Personal Weapons

In [26]:
# TYPES OF CRIMES AT DISPENSARIES
# N = 751 TOTAL CRIMES AT A MARIJUANA BUSINESS
# MOST (56%, n = 418) ARE BURGLARY FOLLOWED BY ROBBERY (15%, n = 114)
weedStore_df = crime_df.loc[(crime_df['Premise'] == "Marijuana Business")]

In [27]:
weedStore_df["Crime_Type"].value_counts()

Burglary               418
Robbery                114
Assault                 89
Theft                   79
Arson                    7
Homicide                 3
Rape/Sexual Assault      1
Name: Crime_Type, dtype: int64

In [28]:
# There were 157,601 crimes at non-marijuna retail stores
retailStore_df = crime_df.loc[(crime_df['Premise'] == "Retail Location")] 
retailStore_df.head()

,Year,Date_Occur,LAPD_Area,LAPD_Area_Name,LAT,LON,Crime_Type,Premise,Weapon
0,2013,09/27/2013,8,West LA,34.0620,-118.4480,Burglary,Retail Location,NaN
17,2013,07/14/2013,2,Rampart,34.0565,-118.2768,Theft,Retail Location,NaN
24,2013,09/18/2013,1,Central,34.0423,-118.2595,Burglary,Retail Location,NaN
28,2013,03/29/2013,7,Wilshire,34.0516,-118.3671,Burglary,Retail Location,NaN
32,2013,11/13/2013,14,Pacific,34.0187,-118.4069,Theft,Retail Location,NaN

In [29]:
# Of the 157,601 crimes at retail stores, most (59%, n = 93,567) were theft
retailStore_df["Crime_Type"].value_counts()

Theft                  93567
Assault                17216
Burglary               15047
Robbery                13434
Rape/Sexual Assault     1708
Arson                    282
Homicide                  55
Name: Crime_Type, dtype: int64

In [30]:
crime_df["Year"].value_counts()

2017    153853
2018    153687
2016    148668
2019    146218
2015    140191
2014    126792
2013    126752
Name: Year, dtype: int64

In [ ]:
crime_df["Year"].value_counts()

In [35]:
# OUTPUT TO CSV SO CAN USE FILE FOR OTHER PURPOSES
crime_df.to_csv(r'../static/data/source/revised_crime_data.csv', index=False)

In [33]:
crime_2013_df = crime_df.loc[(crime_df["Year"] == 2013)]
crime_2014_df = crime_df.loc[(crime_df["Year"] == 2014)]
crime_2015_df = crime_df.loc[(crime_df["Year"] == 2015)]
crime_2016_df = crime_df.loc[(crime_df["Year"] == 2016)]
crime_2017_df = crime_df.loc[(crime_df["Year"] == 2017)]
crime_2018_df = crime_df.loc[(crime_df["Year"] == 2018)]
crime_2019_df = crime_df.loc[(crime_df["Year"] == 2019)]

In [34]:
crime_df.to_json(r'JSON Files/crime.JSON', orient = "index")
crime_2013_df.to_json(r'JSON Files/crime_2013.json', orient = "index")
crime_2014_df.to_json(r'JSON Files/crime_2014.json', orient = "index")
crime_2015_df.to_json(r'JSON Files/crime_2015.json', orient = "index")
crime_2016_df.to_json(r'JSON Files/crime_2016.json', orient = "index")
crime_2017_df.to_json(r'JSON Files/crime_2017.json', orient = "index")
crime_2018_df.to_json(r'JSON Files/crime_2018.json', orient = "index")
crime_2019_df.to_json(r'JSON Files/crime_2019.json', orient = "index")